### PR TITLE
Port samples to SDK 2.0

### PR DESCRIPTION
**Pull request by torbsorb**
- Updates to all samples
- Updated CMakeLists for Zivid 2.0 compatibility
- Updated README version info to Zivid 2.0

### CODE REVIEW

**Comment by eskaur** [comment]
This is literally the same as what I approved in the other repo, right?

**Comment by eskaur** [comment]
> This is literally the same as what I approved in the other repo, right?

Edit, no, I think the rebase is messed up.

**Comment by eskaur** [comment]
The code in the first commit doesn't compile btw.

**Comment by chrisasc** [comment]
> This is literally the same as what I approved in the other repo, right?
yes, this is exactly the same as you did Eskil

**Comment by eskaur** [comment]
> The code in the first commit doesn't compile btw.

Not saying you should spend a lot of time making them valid commits, but perhaps they should just be squashed if the intermediate state is invalid anyway. @chrisasc @SatjaSivcev

**Pull request closed without merging**
